# Generated by Django 5.1.7 on 2025-03-07 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id_autor', models.AutoField(db_column='T001IdAutor', editable=False, primary_key=True, serialize=False)),
                ('nombre_Autor', models.CharField(db_column='T001NombreAutor', max_length=100)),
                ('apellido_Autor', models.CharField(db_column='T001ApellidoAutor', max_length=100)),
                ('biografia_Autor', models.CharField(db_column='T001BiografiaAutor', max_length=1000)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'db_table': 'T001Autor',
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id_Editorial', models.AutoField(db_column='T002IdEditorial', editable=False, primary_key=True, serialize=False)),
                ('nombre_Editorial', models.CharField(db_column='TOO2NombreEditorial', max_length=100)),
                ('direccion_Editorial', models.CharField(db_column='T002DirecionEditorial', max_length=100)),
                ('telefono_Editorial', models.CharField(db_column='T002TelefonoEditorial', max_length=20)),
            ],
            options={
                'verbose_name': 'Editorial',
                'verbose_name_plural': 'Editoriales',
                'db_table': 'T002Editorial',
            },
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('Id_miembro', models.AutoField(db_column='T004IdMiembro', editable=False, primary_key=True, serialize=False)),
                ('nombre_miembro', models.CharField(db_column='T004NombreMiembro', max_length=100)),
                ('apellido_miembro', models.CharField(db_column='T004ApellidoMiembro', max_length=100)),
                ('email_Mienbro', models.CharField(db_column='T004Email', unique=True)),
                ('fechamembresia', models.DateField(db_column='T004FechaMembresia')),
            ],
            options={
                'verbose_name': 'Miembro',
                'verbose_name_plural': 'Miembros',
                'db_table': 'T004Miembro',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id_libro', models.AutoField(db_column='T003IdLibro', editable=False, primary_key=True, serialize=False)),
                ('titulo_libro', models.CharField(db_column='T003TituloLibro', max_length=100)),
                ('resumen_libro', models.CharField(db_column='T003ResumenLibro', max_length=100)),
                ('ISBN_libro', models.CharField(db_column='T003ISBNLibro', max_length=40)),
                ('aniopublicacion_libro', models.DateField(db_column='T003AñoPublicacion')),
                ('autor', models.ForeignKey(db_column='T003IdAutor', on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='api_app.autor')),
                ('editorial', models.ForeignKey(db_column='T003IdEditorial', on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='api_app.editorial')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'db_table': 'T003Libro',
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('Id_prestamo', models.AutoField(db_column='T005IdPrestamo', editable=False, primary_key=True, serialize=False)),
                ('fecha_prestamo', models.DateField(db_column='T005FechaPrestamo')),
                ('fecha_devolucion', models.DateField(blank=True, db_column='T006FechaDevolucion', null=True)),
                ('libro', models.ForeignKey(db_column='T005IdLibros', on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='api_app.libro')),
                ('miembro', models.ForeignKey(db_column='T005IdMiembro', on_delete=django.db.models.deletion.CASCADE, related_name='mienbros', to='api_app.miembro')),
            ],
            options={
                'verbose_name': 'Prestamo',
                'verbose_name_plural': 'Prestamo',
                'db_table': 'T005Prestamo',
            },
        ),
    ]
